trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    artifactName: 'CreateResourceGroupArtifact'
    path: $(System.ArtifactsDirectory)
    displayName: 'Download pipeline artifact'

- task: DownloadSecureFile@1
  name: 'Download ARM Template'
  inputs:
    secureFile: 'CreateResourceGroupARMTemplate'
  displayName: 'Download secure file'

- task: AzureCLI@2
  displayName: 'Deploy ARM Template'
  inputs:
    azureSubscription: 'Azure Subscription Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment create \
        --name FirstDeployment \
        --location eastus \
        --template-file $(System.ArtifactsDirectory)/CreateResourceGroupArtifact/CreateResourceGroupARMTemplate