name: Bicep Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            az upgrade --yes
            az extension add --name bicep

      - name: Build Bicep file
        run: az bicep build --file "Create_RG_in_Azure/ResourceGroup.bicep" --outfile "Create_RG_in_Azure/ResourceGroup.json"


      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Build Bicep file"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
