name: Azure Resource Group Deployment
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DINO_SMILES_CREDENTIALS }}
      - uses: azure/bicep@v0.4.116
        with:
          args: build ResourceGroup.bicep
      - uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment sub create --name myDeployment --location canadacentral --template-file ResourceGroup.bicep
