name: Azure Deployment

on:
  push:
    branches:
      - main
      
env:
  BICEP_FILE_NAME: "ResourceGroup"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and login to Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Compile Bicep to ARM template (JSON)
        run: az bicep build --file ${{ env.BICEP_FILE_NAME }}.bicep --outfile ${{ env.BICEP_FILE_NAME }}.json

      - name: Create Resource Group
        run: az deployment sub create --name RGAttempt1 --location eastus --template-uri https://raw.githubusercontent.com/SN705/Create_RG_in_Azure/main/${{ env.BICEP_FILE_NAME }}.json

        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
